const TIPO_INSTRUCCION = {
    COUT: 'INST_COUT',
    DECLARACION: 'DECLARACION',
    ASIGNACION: 'ASIGNACION',
    WHILE: 'WHILE',
    DOWHILE: 'DOWHILE',
    FOR: 'FOR',
    DEC_METODO: 'DEC_METODO',
    DEC_FUNCION: 'DEC_FUNCION',
    EXEC: 'EXEC',
    LLAMADA: 'LLAMADA',
    IF: 'IF',
    IF_ELSE: 'IF_ELSE',
    BREAK: 'BREAK',
    CONTINUE: 'CONTINUE',
    RETURN: 'RETURN'
}

module.exports = TIPO_INSTRUCCION